client_config_backend: settings
client_config:
client_id: your_client_id
client_secret: your_client_secretsave_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.jsonget_refresh_token: Trueoauth_scope:
- https://www.googleapis.com/auth/drive.fil